module.exports = {
  order: [
    'custom-properties',
    'dollar-variables',
    {
      type: 'at-rule',
      name: 'include',
    },
    {
      type: 'at-rule',
      name: 'include',
      hasBlock: true,
    },
    'declarations',
    {
      type: 'rule',
      selector: /^&/,
    },
    {
      type: 'rule',
      selector: /^&:\w+$/,
    },
    {
      type: 'rule',
      selector: /^&::\w+$/,
    },
    {
      type: 'at-rule',
      name: 'media',
    },
  ],
  propertiesOrder: [
    'pointer-events',
    'visibility',
    'position',
    'top',
    'right',
    'bottom',
    'left',
    'isolation',
    'z-index',
    'order',
    'grid-column',
    'grid-column-start',
    'grid-column-end',
    'grid-row',
    'grid-row-start',
    'grid-row-end',
    'float',
    'clear',
    'margin',
    'margin-top',
    'margin-right',
    'margin-bottom',
    'margin-left',
    'box-sizing',
    'display',
    'height',
    'max-height',
    'min-height',
    'width',
    'min-width',
    'max-width',
    'flex',
    'flex-shrink',
    'flex-grow',
    'table-layout',
    'border-collapse',
    'transform-origin',
    'transform',
    'animation',
    'animation-name',
    'animation-duration',
    'animation-timing-function',
    'animation-delay',
    'animation-iteration-count',
    'animation-direction',
    'animation-fill-mode',
    'animation-play-state',
    'cursor',
    'user-select',
    'resize',
    'list-style-position',
    'list-style-type',
    'appearance',
    'grid-auto-columns',
    'grid-auto-flow',
    'grid-auto-rows',
    'grid-template-columns',
    'grid-template-rows',
    'flex-direction',
    'flex-wrap',
    'place-content',
    'place-items',
    'align-content',
    'align-items',
    'justify-content',
    'justify-items',
    'gap',
    'column-gap',
    'row-gap',
    'place-self',
    'align-self',
    'justify-self',
    'overflow',
    'overscroll-behavior',
    'text-overflow',
    'white-space',
    'overflow-wrap',
    'word-break',
    'border-radius',
    'border-width',
    'border-style',
    'border-color',
    'background-color',
    'background',
    'background-image',
    'box-decoration-break',
    'background-size',
    'background-attachment',
    'background-clip',
    'background-position',
    'background-repeat',
    'background-origin',
    'fill',
    'stroke',
    'stroke-width',
    'object-fit',
    'object-position',
    'padding',
    'padding-top',
    'padding-right',
    'padding-bottom',
    'padding-left',
    'text-align',
    'vertical-align',
    'font-family',
    'font-size',
    'font-weight',
    'text-transform',
    'font-style',
    'font-variant-numeric',
    'line-height',
    'letter-spacing',
    'color',
    'text-decoration',
    'text-shadow',
    '-webkit-font-smoothing',
    '-moz-osx-font-smoothing',
    'caret-color',
    'opacity',
    'background-blend-mode',
    'mix-blend-mode',
    'box-shadow',
    'outline',
    'outline-offset',
    'filter',
    'backdrop-filter',
    'transition-property',
    'transition-delay',
    'transition-duration',
    'transition-timing-function',
  ],
};
